---
- name: Open grafana port (firewalld)
  ansible.posix.firewalld:
    port: "{{ grafana_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  when: ansible_facts.services['firewalld.service'] is defined
  ignore_errors: true

- name: Open grafana port (ufw)
  community.general.ufw:
    rule: allow
    port: "{{ grafana_port }}"
    proto: tcp
  when: ansible_facts.packages['ufw'] is defined
  ignore_errors: true
