---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        timeout: 60

    - name: Gather facts
      ansible.builtin.setup:

    - name: Install unzip
      ansible.builtin.package:
        name: unzip
        state: present
