#!/usr/bin/env bash
# ==============================================================================
# make_airgap.sh
# Run on an internet-connected machine to produce install_exporters_airgap.sh
# with all binaries embedded as gzip+base64 blobs.
#
# Usage:
#   bash make_airgap.sh              # amd64 only (default)
#   bash make_airgap.sh --arch all   # amd64 + arm64
# ==============================================================================
set -euo pipefail

ARCHES=("amd64")
OUTPUT="install_exporters_airgap.sh"

while [[ $# -gt 0 ]]; do
  case $1 in
    --arch) [[ "$2" == "all" ]] && ARCHES=(amd64 arm64) || ARCHES=("$2"); shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

# Keep in sync with install_exporters.sh
NODE_EXPORTER_VERSION="1.11.0"
ALLOY_VERSION="1.16.1"
POSTGRES_EXPORTER_VERSION="0.16.0"
MONGODB_EXPORTER_VERSION="0.40.0"

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

RED='\033[0;31m'; GREEN='\033[0;32m'; BOLD='\033[1m'; NC='\033[0m'
log()  { echo -e "${GREEN}[+]${NC} $*"; }
warn() { echo -e "\033[1;33m[!]${NC} $*"; }
die()  { echo -e "${RED}[✗]${NC} $*" >&2; exit 1; }

command -v curl    &>/dev/null || die "curl required"
command -v gzip    &>/dev/null || die "gzip required"
command -v base64  &>/dev/null || die "base64 required"
command -v tar     &>/dev/null || die "tar required"
command -v unzip   &>/dev/null || die "unzip required"

fetch() {
  local url=$1 dest=$2
  log "Downloading $(basename "$dest")..."
  curl -fsSL --retry 3 --retry-delay 2 "$url" -o "$dest"
}

# gzip compress then base64 encode; prints result to stdout
encode() { gzip -c "$1" | base64 -w0; }

declare -A BLOB

for ARCH in "${ARCHES[@]}"; do
  log "━━━ arch: ${ARCH} ━━━"

  # ── node_exporter ────────────────────────────────────────────────────────────
  NE_ARCH="node_exporter-${NODE_EXPORTER_VERSION}.linux-${ARCH}.tar.gz"
  fetch "https://github.com/prometheus/node_exporter/releases/download/v${NODE_EXPORTER_VERSION}/${NE_ARCH}" \
        "$TMPDIR/$NE_ARCH"
  tar -xzf "$TMPDIR/$NE_ARCH" -C "$TMPDIR"
  BLOB["NODE_EXPORTER_${ARCH^^}"]=$(encode "$TMPDIR/node_exporter-${NODE_EXPORTER_VERSION}.linux-${ARCH}/node_exporter")
  log "node_exporter ${ARCH}: $(echo "${BLOB["NODE_EXPORTER_${ARCH^^}"]}" | wc -c | numfmt --to=iec) base64"

  # ── alloy ────────────────────────────────────────────────────────────────────
  ALLOY_ARCH="alloy-linux-${ARCH}.zip"
  fetch "https://github.com/grafana/alloy/releases/download/v${ALLOY_VERSION}/${ALLOY_ARCH}" \
        "$TMPDIR/$ALLOY_ARCH"
  unzip -o "$TMPDIR/$ALLOY_ARCH" "alloy-linux-${ARCH}" -d "$TMPDIR" >/dev/null
  BLOB["ALLOY_${ARCH^^}"]=$(encode "$TMPDIR/alloy-linux-${ARCH}")
  log "alloy ${ARCH}: $(echo "${BLOB["ALLOY_${ARCH^^}"]}" | wc -c | numfmt --to=iec) base64"

  # ── postgres_exporter ────────────────────────────────────────────────────────
  PG_ARCH="postgres_exporter-${POSTGRES_EXPORTER_VERSION}.linux-${ARCH}.tar.gz"
  fetch "https://github.com/prometheus-community/postgres_exporter/releases/download/v${POSTGRES_EXPORTER_VERSION}/${PG_ARCH}" \
        "$TMPDIR/$PG_ARCH"
  tar -xzf "$TMPDIR/$PG_ARCH" -C "$TMPDIR"
  BLOB["POSTGRES_EXPORTER_${ARCH^^}"]=$(encode "$TMPDIR/postgres_exporter-${POSTGRES_EXPORTER_VERSION}.linux-${ARCH}/postgres_exporter")
  log "postgres_exporter ${ARCH}: $(echo "${BLOB["POSTGRES_EXPORTER_${ARCH^^}"]}" | wc -c | numfmt --to=iec) base64"

  # ── mongodb_exporter (optional) ──────────────────────────────────────────────
  MG_ARCH="mongodb_exporter-${MONGODB_EXPORTER_VERSION}.linux-${ARCH}.tar.gz"
  if curl -fsSL --retry 2 \
       "https://github.com/percona/mongodb_exporter/releases/download/v${MONGODB_EXPORTER_VERSION}/${MG_ARCH}" \
       -o "$TMPDIR/$MG_ARCH" 2>/dev/null; then
    tar -xzf "$TMPDIR/$MG_ARCH" -C "$TMPDIR"
    BLOB["MONGODB_EXPORTER_${ARCH^^}"]=$(encode "$TMPDIR/mongodb_exporter")
    log "mongodb_exporter ${ARCH}: $(echo "${BLOB["MONGODB_EXPORTER_${ARCH^^}"]}" | wc -c | numfmt --to=iec) base64"
  else
    warn "mongodb_exporter download failed — will be skipped in airgap script"
    BLOB["MONGODB_EXPORTER_${ARCH^^}"]=""
  fi
done

# Fill empty arch blobs so the generated script has all vars defined
for BINARY in NODE_EXPORTER ALLOY POSTGRES_EXPORTER MONGODB_EXPORTER; do
  for ARCH in AMD64 ARM64; do
    : "${BLOB["${BINARY}_${ARCH}"]=""}"
  done
done

log "━━━ Generating ${OUTPUT} ━━━"

cat > "$OUTPUT" << SCRIPT_HEAD
#!/usr/bin/env bash
# ==============================================================================
# install_exporters_airgap.sh  —  AUTO-GENERATED by make_airgap.sh
# Self-contained: all binaries embedded as gzip+base64 blobs.
# No internet access required.
#
# Generated: $(date -u '+%Y-%m-%d %H:%M UTC')
# Versions:  node_exporter=${NODE_EXPORTER_VERSION}  alloy=${ALLOY_VERSION}
#            postgres_exporter=${POSTGRES_EXPORTER_VERSION}  mongodb_exporter=${MONGODB_EXPORTER_VERSION}
# ==============================================================================
set -euo pipefail

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  CONFIGURATION — edit before running                                       ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
MONITORING_SERVER_IP="192.168.88.11"
LOG_SOURCE="docker"
FILE_LOG_PATHS=(
  "/var/log/*.log"
  "/var/log/app/*.log"
)
POSTGRES_DSN="postgresql://postgres_exporter:CHANGE_ME@localhost:5432/postgres?sslmode=disable"
MONGODB_URI="mongodb://localhost:27017/"

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  EMBEDDED BINARIES (gzip + base64)                                         ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
SCRIPT_HEAD

# Write blob variables
for KEY in "${!BLOB[@]}"; do
  printf 'BLOB_%s=%s\n' "$KEY" "'${BLOB[$KEY]}'" >> "$OUTPUT"
done

cat >> "$OUTPUT" << 'SCRIPT_BODY'

# ══════════════════════════════════════════════════════════════════════════════
# INTERNALS
# ══════════════════════════════════════════════════════════════════════════════

ARCH_RAW=$(uname -m)
[[ "$ARCH_RAW" == "aarch64" ]] && ARCH="arm64" || ARCH="amd64"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'
log()  { echo -e "${GREEN}[+]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
die()  { echo -e "${RED}[✗]${NC} $*" >&2; exit 1; }
step() { echo -e "\n${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n${BOLD}   $*${NC}\n${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"; }

[[ $EUID -eq 0 ]] || die "Run as root: sudo bash $0"

preflight() {
  local missing=()
  for cmd in gzip tar sha256sum systemctl useradd install ss; do
    command -v "$cmd" &>/dev/null || missing+=("$cmd")
  done
  [[ ${#missing[@]} -eq 0 ]] || die "Missing required tools: ${missing[*]}"
  log "Pre-flight OK"
}

create_user() {
  id "$1" &>/dev/null || useradd --system --no-create-home --shell /sbin/nologin "$1"
}

# Decode gzip+base64 blob to destination path
extract_embedded() {
  local blob_var=$1 dest=$2
  local blob="${!blob_var}"
  [[ -n "$blob" ]] || die "Embedded binary '${blob_var}' is empty — regenerate with make_airgap.sh"
  log "Extracting $(basename "$dest") from embedded blob..."
  echo "$blob" | base64 -d | gzip -d > "$dest"
  chmod 0755 "$dest"
}

open_port() {
  local port=$1
  if command -v firewall-cmd &>/dev/null && firewall-cmd --state &>/dev/null 2>&1; then
    firewall-cmd --permanent --add-port="${port}/tcp" &>/dev/null
    firewall-cmd --reload &>/dev/null
    log "firewalld: opened ${port}/tcp"
  fi
}

svc_enable() {
  systemctl daemon-reload
  systemctl enable --now "$1"
  log "$1 enabled and started"
}

already_installed() {
  local binary=$1 version=$2
  "$binary" --version 2>&1 | grep -qF "$version" 2>/dev/null
}

has_postgres() {
  systemctl is-active --quiet postgresql      2>/dev/null && return 0
  systemctl is-active --quiet "postgresql-*" 2>/dev/null && return 0
  ss -tlnp 2>/dev/null | grep -q ':5432 '    && return 0
  return 1
}

has_mongodb() {
  systemctl is-active --quiet mongod 2>/dev/null && return 0
  ss -tlnp 2>/dev/null | grep -q ':27017 '   && return 0
  return 1
}

# ── Node Exporter ─────────────────────────────────────────────────────────────

install_node_exporter() {
  step "Node Exporter (airgap)"

  if already_installed /usr/local/bin/node_exporter ""; then
    log "node_exporter already installed, skipping"
  else
    extract_embedded "BLOB_NODE_EXPORTER_${ARCH^^}" /usr/local/bin/node_exporter
  fi

  create_user node_exporter

  cat > /etc/systemd/system/node_exporter.service << 'UNIT'
[Unit]
Description=Node Exporter
After=network-online.target
Wants=network-online.target

[Service]
User=node_exporter
Group=node_exporter
Type=simple
ExecStart=/usr/local/bin/node_exporter
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
UNIT

  svc_enable node_exporter
  open_port 9100
}

# ── Alloy ─────────────────────────────────────────────────────────────────────

install_alloy() {
  step "Alloy (airgap, log shipping to ${MONITORING_SERVER_IP})"

  if already_installed /usr/local/bin/alloy ""; then
    log "alloy already installed, skipping"
  else
    extract_embedded "BLOB_ALLOY_${ARCH^^}" /usr/local/bin/alloy
  fi

  create_user alloy
  install -d -o alloy -g alloy -m 0755 /etc/alloy /var/lib/alloy

  _write_alloy_config

  if [[ "$LOG_SOURCE" == "docker" ]] && getent group docker &>/dev/null; then
    usermod -aG docker alloy
    log "Added alloy to docker group"
  fi

  cat > /etc/systemd/system/alloy.service << 'UNIT'
[Unit]
Description=Grafana Alloy
After=network-online.target
Wants=network-online.target

[Service]
User=alloy
Group=alloy
Type=simple
ExecStart=/usr/local/bin/alloy run /etc/alloy/config.alloy --storage.path=/var/lib/alloy
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
UNIT

  svc_enable alloy
  open_port 12345
}

_write_alloy_config() {
  local hostname loki_url
  hostname=$(hostname -f)
  loki_url="http://${MONITORING_SERVER_IP}:3100/loki/api/v1/push"

  log "Writing Alloy config (log_source=${LOG_SOURCE})..."

  cat > /etc/alloy/config.alloy << EOF
// Alloy config — generated by install_exporters_airgap.sh
// Host: ${hostname} | Loki: ${loki_url}

// ── Journal logs (always shipped) ────────────────────────────────────────────
loki.source.journal "journal" {
  forward_to    = [loki.write.default.receiver]
  relabel_rules = loki.relabel.journal.rules
  labels = {
    host = "${hostname}",
    job  = "journal",
  }
}

loki.relabel "journal" {
  forward_to = []
  rule {
    source_labels = ["__journal__systemd_unit"]
    target_label  = "unit"
  }
  rule {
    source_labels = ["__journal__priority_keyword"]
    target_label  = "level"
  }
}

EOF

  if [[ "$LOG_SOURCE" == "docker" ]]; then
    cat >> /etc/alloy/config.alloy << EOF
// ── Docker container logs ─────────────────────────────────────────────────────
discovery.docker "containers" {
  host = "unix:///var/run/docker.sock"
}

loki.source.docker "docker_logs" {
  host          = "unix:///var/run/docker.sock"
  targets       = discovery.docker.containers.targets
  forward_to    = [loki.write.default.receiver]
  relabel_rules = loki.relabel.docker.rules
}

loki.relabel "docker" {
  forward_to = []
  rule {
    source_labels = ["__meta_docker_container_name"]
    regex         = "/(.*)"
    target_label  = "container"
  }
  rule {
    source_labels = ["__meta_docker_container_image"]
    target_label  = "image"
  }
  rule {
    replacement  = "${hostname}"
    target_label = "host"
  }
}

EOF
  else
    local path_entries=""
    for p in "${FILE_LOG_PATHS[@]}"; do
      path_entries+="{\"__path__\" = \"${p}\", \"host\" = \"${hostname}\", \"job\" = \"file\"},"$'\n    '
    done

    cat >> /etc/alloy/config.alloy << EOF
// ── File-based log collection ─────────────────────────────────────────────────
local.file_match "app_logs" {
  path_targets = [
    ${path_entries}]
}

loki.source.file "file_logs" {
  targets    = local.file_match.app_logs.targets
  forward_to = [loki.write.default.receiver]
}

EOF
  fi

  cat >> /etc/alloy/config.alloy << EOF
// ── Loki write endpoint ───────────────────────────────────────────────────────
loki.write "default" {
  endpoint {
    url = "${loki_url}"
  }
}
EOF

  chown alloy:alloy /etc/alloy/config.alloy
}

# ── PostgreSQL Exporter ───────────────────────────────────────────────────────

install_postgres_exporter() {
  step "postgres_exporter (airgap)"

  if already_installed /usr/local/bin/postgres_exporter ""; then
    log "postgres_exporter already installed, skipping"
  else
    extract_embedded "BLOB_POSTGRES_EXPORTER_${ARCH^^}" /usr/local/bin/postgres_exporter
  fi

  create_user postgres_exporter
  install -d -m 0750 /etc/postgres_exporter

  printf 'DATA_SOURCE_NAME=%s\n' "$POSTGRES_DSN" \
    > /etc/postgres_exporter/postgres_exporter.env
  chmod 0600 /etc/postgres_exporter/postgres_exporter.env
  chown postgres_exporter:postgres_exporter /etc/postgres_exporter/postgres_exporter.env

  cat > /etc/systemd/system/postgres_exporter.service << 'UNIT'
[Unit]
Description=PostgreSQL Exporter
After=network-online.target postgresql.service
Wants=network-online.target

[Service]
User=postgres_exporter
Group=postgres_exporter
Type=simple
EnvironmentFile=/etc/postgres_exporter/postgres_exporter.env
ExecStart=/usr/local/bin/postgres_exporter
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
UNIT

  svc_enable postgres_exporter
  open_port 9187
}

# ── MongoDB Exporter ──────────────────────────────────────────────────────────

install_mongodb_exporter() {
  step "mongodb_exporter (airgap)"

  local blob_var="BLOB_MONGODB_EXPORTER_${ARCH^^}"
  [[ -n "${!blob_var}" ]] || die "MongoDB exporter blob is empty. Regenerate with: bash make_airgap.sh"

  if already_installed /usr/local/bin/mongodb_exporter ""; then
    log "mongodb_exporter already installed, skipping"
  else
    extract_embedded "$blob_var" /usr/local/bin/mongodb_exporter
  fi

  create_user mongodb_exporter
  install -d -m 0750 /etc/mongodb_exporter

  printf 'MONGODB_URI=%s\n' "$MONGODB_URI" \
    > /etc/mongodb_exporter/mongodb_exporter.env
  chmod 0600 /etc/mongodb_exporter/mongodb_exporter.env
  chown mongodb_exporter:mongodb_exporter /etc/mongodb_exporter/mongodb_exporter.env

  cat > /etc/systemd/system/mongodb_exporter.service << 'UNIT'
[Unit]
Description=MongoDB Exporter
After=network-online.target mongod.service
Wants=network-online.target

[Service]
User=mongodb_exporter
Group=mongodb_exporter
Type=simple
EnvironmentFile=/etc/mongodb_exporter/mongodb_exporter.env
ExecStart=/usr/local/bin/mongodb_exporter --collect-all
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
UNIT

  svc_enable mongodb_exporter
  open_port 9216
}

# ── Main ──────────────────────────────────────────────────────────────────────

main() {
  echo -e "${BOLD}"
  echo "╔══════════════════════════════════════════════════╗"
  echo "║   Exporter Installer (AIR-GAP MODE)              ║"
  echo "║   Rocky Linux / RHEL / AlmaLinux / Ubuntu        ║"
  echo "╚══════════════════════════════════════════════════╝"
  echo -e "${NC}"
  log "Arch: ${ARCH} | Monitoring server: ${MONITORING_SERVER_IP} | Log source: ${LOG_SOURCE}"

  preflight

  install_node_exporter
  install_alloy

  if has_postgres; then
    log "PostgreSQL detected → installing postgres_exporter"
    [[ "$POSTGRES_DSN" != *"CHANGE_ME"* ]] || \
      warn "POSTGRES_DSN contains CHANGE_ME — update before using in production"
    install_postgres_exporter
  else
    log "PostgreSQL not detected — skipping postgres_exporter"
  fi

  if has_mongodb; then
    log "MongoDB detected → installing mongodb_exporter"
    install_mongodb_exporter
  else
    log "MongoDB not detected — skipping mongodb_exporter"
  fi

  local server_ip
  server_ip=$(hostname -I | awk '{print $1}')
  echo ""
  echo -e "${GREEN}Installation complete!${NC}"
  echo ""
  printf "  %-20s http://%s:9100/metrics\n" "Node Exporter:" "$server_ip"
  printf "  %-20s http://%s:12345\n"        "Alloy UI:"      "$server_ip"
  systemctl is-active --quiet postgres_exporter 2>/dev/null && \
    printf "  %-20s http://%s:9187/metrics\n" "PG Exporter:" "$server_ip" || true
  systemctl is-active --quiet mongodb_exporter 2>/dev/null && \
    printf "  %-20s http://%s:9216/metrics\n" "Mongo Exporter:" "$server_ip" || true
  echo ""
  echo "  Logs ship to: http://${MONITORING_SERVER_IP}:3100"
}

main "$@"
SCRIPT_BODY

chmod +x "$OUTPUT"

SIZE=$(du -sh "$OUTPUT" | cut -f1)
log "Done! Generated: ${OUTPUT} (${SIZE})"
echo ""
echo "  Copy to air-gapped server:"
echo "    scp ${OUTPUT} root@<target-ip>:/tmp/"
echo "    ssh root@<target-ip> 'bash /tmp/${OUTPUT}'"
