---
mongodb_exporter_version: "0.40.0"
mongodb_exporter_port: 9216
mongodb_exporter_user: "mongodb_exporter"
mongodb_exporter_group: "mongodb_exporter"
mongodb_exporter_install_dir: "/usr/local/bin"
mongodb_exporter_config_dir: "/etc/mongodb_exporter"
mongodb_exporter_checksum: {}
mongodb_exporter_uri: ""
