---
galaxy_info:
  role_name: alertmanager
  description: "Ansible role to deploy and manage alertmanager on Linux systems"
  author: monitoring-simple
  license: MIT
  min_ansible_version: "2.13"
dependencies: []
