---
galaxy_info:
  role_name: mongodb_exporter
  description: "Ansible role to deploy and manage mongodb exporter on Linux systems"
  author: monitoring-simple
  license: MIT
  min_ansible_version: "2.13"
dependencies: []
