---
galaxy_info:
  role_name: postgres_exporter
  description: "Ansible role to deploy and manage postgres exporter on Linux systems"
  author: monitoring-simple
  license: MIT
  min_ansible_version: "2.13"
dependencies: []
