---
galaxy_info:
  role_name: prometheus
  description: "Ansible role to deploy and manage prometheus on Linux systems"
  author: monitoring-simple
  license: MIT
  min_ansible_version: "2.13"
dependencies: []
