---
- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    daemon_reload: true

- name: Reload prometheus
  ansible.builtin.uri:
    url: "http://localhost:{{ prometheus_port }}/-/reload"
    method: POST
    status_code: 200
