---
- name: Create mongodb_exporter system user
  ansible.builtin.user:
    name: "{{ mongodb_exporter_user }}"
    group: "{{ mongodb_exporter_group }}"
    system: true
    shell: /sbin/nologin
    create_home: false

- name: Create config directory
  ansible.builtin.file:
    path: "{{ mongodb_exporter_config_dir }}"
    state: directory
    owner: "{{ mongodb_exporter_user }}"
    group: "{{ mongodb_exporter_group }}"
    mode: "0750"

- name: Run install tasks
  ansible.builtin.import_tasks: install.yml
- name: Run configure tasks
  ansible.builtin.import_tasks: configure.yml
- name: Run service tasks
  ansible.builtin.import_tasks: service.yml
- name: Run firewall tasks
  ansible.builtin.import_tasks: firewall.yml
